import turtle
turtle.Screen().bgcolor("cyan")
sc = turtle.Screen()
sc.setup(400,400)
turtle.title("Welcome to turtle")
t=turtle.Turtle()
t.forward(100)
t.left(120)
t.forward(100)
t.left(120)
t.forward(100)
t.left(120)
t.penup()
t.goto(-80,50)
t.pendown()
t.fillcolor('red')
t.begin_fill()
t.circle(50)
t.end_fill()
turtle.done()