rf=open('codding.txt','r')
print(rf.read())
rf.close()
af=open('codding.txt','a')
af.write("this text has been apended")
af.close()
rf=open('codding.txt','r')
print(rf.read())
rf.close()
wf=open('codding.txt','w')
wf.write("this text has been writen")
wf.close()
rf=open('codding.txt','r')
print(rf.read())
rf.close()